[package]
name = "parasol-db"
version = "0.1.4"
edition = "2021"
description = "Another database"
license = "BSD-3-Clause"
repository = "https://github.com/tvanderstad/parasol-db/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]